#!/usr/bin/env python3
import os
import sys

def get_paths():
    home = os.environ.get("HOME", os.path.expanduser("~"))
    is_termux = "PREFIX" in os.environ and "com.termux" in os.environ["PREFIX"]

    base_dir = os.path.join(home, ".intimclaw")
    return {
        "is_termux": is_termux,
        "config_dir": base_dir,
        "config_path": os.path.join(base_dir, "config.toml"),
        "skills_dir": os.path.join(base_dir, "skills"),
        "persona_dir": os.path.join(base_dir, "persona"),
        "sessions_dir": os.path.join(base_dir, "sessions"),
        "memory_path": os.path.join(base_dir, "memory.db"),
        "data_dir": base_dir,
    }

def check_config():
    paths = get_paths()
    config_path = paths["config_path"]

    if not os.path.exists(config_path):
        return False

    with open(config_path, "r") as f:
        content = f.read()

    has_provider = False
    has_api_key = False
    for line in content.split("\n"):
        stripped = line.strip()
        if stripped.startswith("provider") and "=" in stripped:
            val = stripped.split("=", 1)[1].strip().strip('"').strip("'")
            if val:
                has_provider = True
        if stripped.startswith("api_key") and "=" in stripped:
            val = stripped.split("=", 1)[1].strip().strip('"').strip("'")
            if val:
                has_api_key = True

    return has_provider and has_api_key

def run_wizard():
    print("\n=======================================================")
    print("         WELCOME TO INTIMCLAW SETUP WIZARD             ")
    print("=======================================================")
    print("This appears to be your first time running IntimClaw.")
    print("Configure your AI Provider to get started.")
    print("-------------------------------------------------------")

    print("\nSelect your primary AI Provider:")
    print("1) Google Gemini (Recommended - Free & Fast)")
    print("2) Anthropic Claude (Smart - Requires API Key)")
    print("3) OpenAI GPT (Industry Standard)")
    print("4) Groq (Fastest Inference)")
    print("5) Custom OpenAI-Compatible (Ollama, LM Studio, etc.)")

    choice = input("\nEnter your choice (1-5): ").strip()

    provider = ""
    default_model = ""
    api_url = ""

    if choice == "1":
        provider = "gemini"
        default_model = "gemini-2.5-flash"
        api_url = "https://generativelanguage.googleapis.com/v1beta"
    elif choice == "2":
        provider = "anthropic"
        default_model = "claude-3-5-sonnet-latest"
        api_url = "https://api.anthropic.com/v1"
    elif choice == "3":
        provider = "openai"
        default_model = "gpt-4o-mini"
        api_url = "https://api.openai.com/v1"
    elif choice == "4":
        provider = "groq"
        default_model = "llama-3.3-70b-versatile"
        api_url = "https://api.groq.com/openai/v1"
    else:
        provider = "custom"
        api_url = input("Enter your API Base URL (e.g. http://localhost:11434/v1): ").strip()
        default_model = input("Enter default model name (e.g. llama3.2): ").strip()

    api_key = input(f"Enter your {provider.upper()} API Key: ").strip()

    if not api_key:
        print("\n[Error] API Key cannot be empty! Setup cancelled.")
        sys.exit(1)

    paths = get_paths()

    os.makedirs(paths["config_dir"], exist_ok=True)
    os.makedirs(paths["skills_dir"], exist_ok=True)
    os.makedirs(paths["persona_dir"], exist_ok=True)

    config_path = paths["config_path"]

    provider_type = "anthropic" if choice == "2" else "openai-compatible"

    # Build providers array-of-tables matching Go struct
    providers_toml = f"""
[[providers]]
name = "{provider}"
type = "{provider_type}"
base_url = "{api_url}"
api_key = "{api_key}"
models = ["{default_model}"]
"""

    # Add reference providers (no API key — user fills in later)
    ref_providers = {
        "gemini": ("openai-compatible", "https://generativelanguage.googleapis.com/v1beta", ["gemini-2.5-flash", "gemini-2.5-pro"]),
        "anthropic": ("anthropic", "https://api.anthropic.com/v1", ["claude-3-5-sonnet-latest"]),
        "openai": ("openai-compatible", "https://api.openai.com/v1", ["gpt-4o-mini", "gpt-4o"]),
        "groq": ("openai-compatible", "https://api.groq.com/openai/v1", ["llama-3.3-70b-versatile"]),
        "ollama": ("openai-compatible", "http://localhost:11434/v1", ["llama3.2", "codellama"]),
    }

    for name, (ptype, purl, pmodels) in ref_providers.items():
        if name != provider:
            models_str = ", ".join(f'"{m}"' for m in pmodels)
            providers_toml += f"""
[[providers]]
name = "{name}"
type = "{ptype}"
base_url = "{purl}"
api_key = ""
models = [{models_str}]
"""

    config_content = f"""# config.toml — IntimClaw Configuration
# Generated by setup wizard

[agent]
name = "intimclaw"
version = "0.1.0"
provider = "{provider}"
model = "{default_model}"
persona = "default"
{providers_toml}
[channels.telegram]
enabled = false
bot_token = ""
owner_id = 0
mention_only = false

[channels.discord]
enabled = false
bot_token = ""

[channels.webchat]
enabled = true
port = 18080
host = "127.0.0.1"

[mcp]
enabled = false

[skills]
enabled = true
directories = ["{paths["skills_dir"]}"]

[memory]
backend = "sqlite"
semantic_search = true
decay_days = 30

[security]
risk_profile = "default"
sandbox = false
excluded_tools = ["rm", "mkfs", "dd", "shutdown", "poweroff"]
forbidden_paths = [".ssh", ".gnupg", ".aws"]

[webui]
enabled = true
port = 18080
host = "127.0.0.1"
theme = "intimclaw"

[cron]
enabled = true
max_jobs = 50
"""

    with open(config_path, "w") as f:
        f.write(config_content)

    # Generate persona/SOUL.md
    soul_path = os.path.join(paths["persona_dir"], "SOUL.md")
    if not os.path.exists(soul_path):
        soul_content = """# SOUL OF INTIMCLAW

You are **IntimClaw**, a capable and efficient AI Agent.

## Communication Style:
- Direct, technical, and efficient.
- Match the operator's energy and language.
- Lead with output. Theory after, only if needed.

## Core Rules:
1. You are an autonomous Agent, not a passive assistant.
2. Use `list_dir` and `file_read` to understand the codebase before making changes.
3. Use `file_write` or `file_edit` to make code changes directly.
4. After editing, run verification commands (e.g. `npm run build`, `python3 script.py`).
5. If errors occur, analyze logs, fix directly, and don't stop until the target is achieved.
"""
        with open(soul_path, "w") as f:
            f.write(soul_content)

    print("=======================================================")
    print("SETUP COMPLETE! Configuration saved to:")
    print(f"   {config_path}")
    print("-------------------------------------------------------")
    print("Starting IntimClaw...")
    print("=======================================================\n")

if __name__ == "__main__":
    if not check_config():
        run_wizard()
    else:
        pass
